spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    br.com.finance: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name}] [correlationId=%X{correlationId:-}] [%thread] %logger{36} - %msg %kvp%n%wEx"