CREATE TABLE application_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    normalized_email VARCHAR(254) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_application_user_normalized_email
        UNIQUE (normalized_email),
    CONSTRAINT ck_application_user_name
        CHECK (CHAR_LENGTH(BTRIM(name)) BETWEEN 2 AND 120),
    CONSTRAINT ck_application_user_timestamps
        CHECK (updated_at >= created_at),
    CONSTRAINT ck_application_user_email
        CHECK (CHAR_LENGTH(BTRIM(email)) BETWEEN 3 AND 254),
    CONSTRAINT ck_application_user_normalized_email
        CHECK (CHAR_LENGTH(BTRIM(normalized_email)) BETWEEN 3 AND 254)
);

CREATE TABLE user_credential (
    user_id BIGINT PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    failed_attempt_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_user_credential_user
        FOREIGN KEY (user_id) REFERENCES application_user (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_credential_failed_attempt_count
        CHECK (failed_attempt_count >= 0),
    CONSTRAINT ck_user_credential_password_hash
        CHECK (CHAR_LENGTH(BTRIM(password_hash)) > 0)
);

CREATE TABLE authentication_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_authentication_session_user
        FOREIGN KEY (user_id) REFERENCES application_user (id),
    CONSTRAINT uk_authentication_session_token_hash
        UNIQUE (token_hash),
    CONSTRAINT ck_authentication_session_token_hash
        CHECK (CHAR_LENGTH(token_hash) = 64),
    CONSTRAINT ck_authentication_session_expiration
        CHECK (expires_at > created_at),
    CONSTRAINT ck_authentication_session_revocation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE TABLE authentication_login_throttle (
    scope VARCHAR(16) NOT NULL,
    key_hash VARCHAR(64) NOT NULL,
    window_started_at TIMESTAMPTZ NOT NULL,
    failure_count INTEGER NOT NULL DEFAULT 0,
    blocked_until TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (scope, key_hash),
    CONSTRAINT ck_authentication_login_throttle_scope
        CHECK (scope IN ('ACCOUNT', 'SOURCE')),
    CONSTRAINT ck_authentication_login_throttle_key_hash
        CHECK (CHAR_LENGTH(key_hash) = 64),
    CONSTRAINT ck_authentication_login_throttle_failure_count
        CHECK (failure_count >= 0),
    CONSTRAINT ck_authentication_login_throttle_updated_at
        CHECK (updated_at >= window_started_at),
    CONSTRAINT ck_authentication_login_throttle_blocked_until
        CHECK (blocked_until IS NULL OR blocked_until > window_started_at)
);

CREATE INDEX idx_authentication_session_user_id
    ON authentication_session (user_id);
